trigger:
- master

resources:
  repositories:
    - repository: P1
      type: git
      name: P1/P1

parameters:
  - name: vmImageName
    type: string
    default: ubuntu-latest
  - name: dockerRegistryServiceConnection
    type: string
    default: 'ee2b5536-159c-48be-b48a-787d78d26abd'
  - name: imageRepository
    type: string
    default: 'vijaymapipelinesdotnetcoredocker'
  - name: containerRegistry
    type: string
    default: 'may14registry.azurecr.io'
  - name: dockerfilePath
    type: string
    default: '**/Dockerfile'
  - name: tag
    type: string
    default: '$(Build.BuildId)'
  - name: imagePullSecret
    type: string
    default: 'may14registry1584dd1c-auth'

extends:
  template: secure-deployment.yml@P1
  parameters:
    vmImageName: ubuntu-latest

    buildSteps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: ${{ parameters.imageRepository }}
        dockerfile: ${{ parameters.dockerfilePath }}
        containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
        tags: |
          ${{ parameters.tag }}

    - upload: manifests
      artifact: manifests

    deployStages:
    - stage: deploy

      jobs:
      - deployment: Deploy
        displayName: Deploy
        pool:
          vmImage: ${{ parameters.vmImageName }}
        environment: 'test.default'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: KubernetesManifest@0
                displayName: Create imagePullSecret
                inputs:
                  action: createSecret
                  secretName: ${{ parameters.imagePullSecret }}
                  dockerRegistryEndpoint: ${{ parameters.dockerRegistryServiceConnection }}
              - task: KubernetesManifest@0
                displayName: Deploy to Kubernetes cluster
                inputs:
                  action: deploy
                  manifests: |
                    $(Pipeline.Workspace)/manifests/deployment.yml
                    $(Pipeline.Workspace)/manifests/service.yml
                  imagePullSecrets: |
                    ${{ parameters.imagePullSecret }}
                  containers: |
                    ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:${{ parameters.tag }}